### ISSUE TITLE
学習と予測を行うロジックの分け方が不適切

### ISSUE THREAD

**Issue by moyomot** [Kxxxxxxxx/assignment#3]
コードを拝見すると学習と予測の流れは下記になっていると思います

```
1. Webフォームからurlを入力
2. その記事データを取得
3. ouptput_categoryファイルから分類器生成
4. カテゴリ予測を実施
```

この流れだと、urlを入力するたびに分類器を生成することになります。
毎回分類器を生成する必要はないと思うので、バッチ処理してください
- バッチ
  - 教師データの取得
  - 教師データを元にした分類器の生成
- Web
  - urlを入力 → 記事データの取得 → 分類予測

学習、予測の関数名も工夫してください
scikit-learnとか参考にすると良いと思います

**Comment by moyomot** [comment]
分類器生成をオンラインで行ってると思いますが、バッチに変更してください
1. train_classify.pyで行ってることをバッチにする
2. 各クラス毎の単語の生起確率等をdictで管理し、pickleでファイルにする
3. 分類するときにpickleファイルを読み込み、予測する

**Comment by moyomot** [comment]
これを再考すると
- get_test_data.py
- get_train_data.py
- train_classify.py
- getmostfrequentwords
  を整理できると思います

**Comment by moyomot** [comment]
どのような方針で修正するか決まったら、コードを変更する前にここにコメントしてください

**Comment by Kxxxxxxxx** [comment]
それでは方針です。
1. 現在のバッチ操作に加えてtrain_classifyの各訓練カテゴリーの生起確率（こちら全て1/8になるため、保存しなくても良いかとは思いました。）と、各クラス毎の単語の生起確率をdictで管理、vocabularyをlistで管理し、pickleで保存
2. train_classifyの中でオンライン上でするのは、得られたテストデータから対数尤度を取り、最大のカテゴリーを返す部分だけで済む。
3. get_train_data.pyの内容はバッチ操作に組み込む
4. get_test_data.pyとgetmostfrequentwordsはテストデータを取るときか訓練データを取るときかで関数内で場合分けし、ひとつの関数で実装

こちらでいかがでしょうか？

**Comment by Kxxxxxxxx** [comment]
先ほどのpull requestにこちらの内容も反映させてみました。
