### ISSUE TITLE
コーディング規約周りの指摘事項

### ISSUE THREAD

**Issue by moyomot** [Kxxxxxxxx/assignment#30]
- 単語間はアンダースコア `_`で区切る、連続して使用しない
- get_train_data.pyを誰がどのように使用するのか不明
  - メソッドが定義されているわけでもない
- `import *` は使用しない
- commandsでは`Command`クラスで実装する
- ファイル操作はwithを使用してclose処理を明記しないようにする
- ソースコードコメントアウトは削除する

**Comment by Kxxxxxxxx** [comment]
get_train_data.pyについてなのですが、
バッチ操作で教師データをファイル出力し、それを
読み込むために使ってみました。
viewsの中で読み込みに使っています。

**Comment by Kxxxxxxxx** [comment]
質問です。

ソースコードコメントアウトというのはプログラムの動作に関係ある
コードをコメントアウトしないということで良いでしょうか？
つまり、操作内容を記した日本語は残しておいても良いということでしょうか？

**Comment by moyomot** [comment]
https://github.com/Kxxxxxxxx/assignment/blob/master/showcategory/get_test_data.py#L17

```
# print('{0} , {1}'.format(word, pos))
```

このような不要なものは削除してください

https://github.com/Kxxxxxxxx/assignment/blob/master/showcategory/get_test_data.py

```
    # 品詞を取得
        pos = node.feature.split(",")[1]
```

一方、このような日本語のコメントは歓迎です。
コメントがあることによって可読性が高まります。
ただし、インデントがずれているので修正してください
