### ISSUE TITLE
views.pyのtrain_classifyについて

### ISSUE THREAD

**Issue by moyomot** [Kxxxxxxxx/assignment#6]
- 引数の `cls, vocabulary, documents, data`がどれも似た用語で違いと捉えるのが困難です
- 引数を見た時にどのようなデータ構造かわからないので、コメントに記載してください
- viewsでこの処理を行うのは不適切ですので、変更お願いします
- 毎回学習する必要はないので、学習と予測は分離したほうが良いと思います
- `各訓練文書の生起回数` 等の各処理は関数に分離したほうが、可読性があがります
- for文のネストが深くて可読性が悪い
  - for文のネストが深くなると、複雑さが増すため単体テストの実装工数も増えます
  - clsは必要でしょうか、documentsのdictのkeyがカテゴリ名のため、自信ないですけどclsなしでも行けそうな気がしました
- 各クラス毎の単語の生起回数について
  - output_allcategoryが必要は、残りのテキストを組み合わせればOKでしょうか？
  - となるとvocabularyが不要になる気がしました

**Comment by Kxxxxxxxx** [comment]
修正のpull requestをあげました。

よろしくお願いします。
